development:
  adapter: postgresql
  encoding: unicode
  database: locale_development
  pool: 5
  username: tdenkin
  password: 1bunnyx

test:
  adapter: postgresql
  encoding: unicode
  database: locale_test
  pool: 5
  username: tdenkin
  password: 1bunnyx

